### ISSUE TITLE
Updater failed to publish to npm

### ISSUE THREAD

**Issue by johnmuhl** [mafintosh/electron-prebuilt#43]
Is there anything I can do help figure out what happened? Were you on 0.1.0 or 0.2.0 when the 0.28.2 release happened?

**Comment by maxogden** [comment]
```
2015-06-18T05:48:51.742161+00:00 app[web.1]: /app/index.js:112
2015-06-18T05:48:51.742165+00:00 app[web.1]:             throw err
2015-06-18T05:48:51.742167+00:00 app[web.1]:                   ^
2015-06-18T05:48:51.742169+00:00 app[web.1]: Error: auth required for publishing
2015-06-18T05:48:51.738920+00:00 app[web.1]: Failed to publish package
2015-06-18T05:48:51.790920+00:00 app[web.1]: npm ERR! Linux 3.13.0-49-generic
2015-06-18T05:48:51.805966+00:00 app[web.1]: npm ERR! Please include the following file with any support request:
2015-06-18T05:48:51.742172+00:00 app[web.1]:     at CachingRegistryClient.publish (/app/node_modules/npm/node_modules/npm-registry-client/lib/publish.js:30:14)
2015-06-18T05:48:51.806127+00:00 app[web.1]: npm ERR!     /app/npm-debug.log
2015-06-18T05:48:51.742173+00:00 app[web.1]:     at /app/node_modules/npm/lib/publish.js:134:14
2015-06-18T05:48:51.742175+00:00 app[web.1]:     at mapToRegistry (/app/node_modules/npm/lib/utils/map-to-registry.js:55:3)
2015-06-18T05:48:51.742177+00:00 app[web.1]:     at publish_ (/app/node_modules/npm/lib/publish.js:104:3)
2015-06-18T05:48:51.742179+00:00 app[web.1]:     at Array.<anonymous> (/app/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
2015-06-18T05:48:51.742180+00:00 app[web.1]:     at LOOP (/app/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
2015-06-18T05:48:51.742182+00:00 app[web.1]:     at /app/node_modules/npm/node_modules/slide/lib/chain.js:18:7
2015-06-18T05:48:51.742184+00:00 app[web.1]:     at done (/app/node_modules/npm/lib/utils/lifecycle.js:105:5)
2015-06-18T05:48:51.742185+00:00 app[web.1]:     at LOOP (/app/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
2015-06-18T05:48:51.742187+00:00 app[web.1]:     at /app/node_modules/npm/node_modules/slide/lib/chain.js:18:7
2015-06-18T05:48:51.742188+00:00 app[web.1]:     at /app/node_modules/npm/lib/utils/lifecycle.js:251:20
2015-06-18T05:48:51.742190+00:00 app[web.1]:     at FSReqWrap.oncomplete (evalmachine.<anonymous>:78:15)
2015-06-18T05:48:51.778020+00:00 app[web.1]: 
```

**Comment by maxogden** [comment]
heres my CONFIG, does this look correct?

```
API_KEY: echo -n 'maxogden:MYPASSWORD' | base64
EMAIL:   max@maxogden.com
OWNER:   mafintosh
REPO:    electron-prebuilt
SECRET:  MYSECRET
TOKEN:   MYTOKEN
```

`MYSECRET` matches what is entered into the webhook config for `atom/electron`, and `MYTOKEN` is an App Specific Token I created (for @maxogden).

**Comment by johnmuhl** [comment]
Is `API_KEY` literally `echo -n 'maxogden:MYPASSWORD' | base64` or the output of that command? It should be the output; e.g `dXNlcjpwYXNzd29yZAo=`

**Comment by maxogden** [comment]
@johnmuhl lol it was literally the command -- good catch!

**Comment by maxogden** [comment]
@johnmuhl updated, hopefully the next publish works

**Comment by johnmuhl** [comment]
@maxogden Glad it was nothing catastrophic.

**Comment by maxogden** [comment]
totally worked this time! https://www.npmjs.com/package/electron-prebuilt

**Comment by johnmuhl** [comment]
:tada: Glad it's working now. Feel free to ping me if there is any trouble in the future.
