### ISSUE TITLE
Error during install: read err { [Error: invalid block type] errno: -3, code: 'Z_DATA_ERROR' }

### ISSUE THREAD

**Issue by ferrylauda** [mafintosh/electron-prebuilt#50]
That's the end of the install log:

```
npm info install electron-prebuilt@0.30.3
npm info postinstall electron-prebuilt@0.30.3

> electron-prebuilt@0.30.3 postinstall /Users/ferrylauda/.nvm/versions/node/v0.12.4/lib/node_modules/electron-prebuilt
> node install.js

read err { [Error: invalid block type] errno: -3, code: 'Z_DATA_ERROR' }
electron-prebuilt@0.30.3 /Users/ferrylauda/.nvm/versions/node/v0.12.4/lib/node_modules/electron-prebuilt
├── extract-zip@1.0.3 (debug@0.7.4, minimist@0.1.0, async@0.9.0, yauzl@2.3.1, mkdirp@0.5.0, through2@0.6.3, concat-stream@1.5.0)
└── electron-download@1.0.7 (path-exists@1.0.0, home-path@0.1.2, debug@2.2.0, mkdirp@0.5.1, mv@2.1.1, nugget@1.5.4)
npm info ok 
```

Notice that the install ended successfully in spite of the error.

Running `electron` from command line fails with:

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn /Users/ferrylauda/.nvm/versions/node/v0.12.4/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

Here are the vesions I'm using:

```
$ npm version
{ npm: '2.10.1',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.4',
  openssl: '1.0.1m',
  uv: '1.5.0',
  v8: '3.28.71.19',
  zlib: '1.2.8' }
```

**Comment by maxogden** [comment]
that usually means the zip file somehow got corrupted. can you delete it from `~/.electron` (if it exists) and try again?

**Comment by ferrylauda** [comment]
it works. thanks for your help

**Comment by mik01aj** [comment]
Still, an error like this should be caught and the install should not continue in this case.
