### ISSUE TITLE
Does not work with electron-rebuild

### ISSUE THREAD

**Issue by nlhkh** [mafintosh/electron-prebuilt#62]
With this error message `Unsupported target version: 0.30.7`.

Here is the full stack track

```
> grabluck@1.0.0 rebuild /Users/khanguyen/CodeProjects/Outsource/grabluck
> electron-rebuild


> fsevents@1.0.0 install /Users/khanguyen/CodeProjects/Outsource/grabluck/node_modules/babel/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

Unsupported target version: 0.30.7

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: Unsupported target version: 0.30.7
node-pre-gyp ERR! stack     at get_runtime_abi (/Users/khanguyen/CodeProjects/Outsource/grabluck/node_modules/babel/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:140:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/Users/khanguyen/CodeProjects/Outsource/grabluck/node_modules/babel/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/versioning.js:249:19)
node-pre-gyp ERR! stack     at install (/Users/khanguyen/CodeProjects/Outsource/grabluck/node_modules/babel/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/install.js:138:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/Users/khanguyen/CodeProjects/Outsource/grabluck/node_modules/babel/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (/Users/khanguyen/CodeProjects/Outsource/grabluck/node_modules/babel/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/khanguyen/CodeProjects/Outsource/grabluck/node_modules/babel/node_modules/chokidar/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:434:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:452:10)
node-pre-gyp ERR! stack     at Module.load (module.js:355:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:310:12)
node-pre-gyp ERR! System Darwin 14.5.0
node-pre-gyp ERR! command "/Users/khanguyen/.nvm/versions/node/v4.1.0/bin/node" "/Users/khanguyen/CodeProjects/Outsource/grabluck/node_modules/babel/node_modules/chokidar/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/khanguyen/CodeProjects/Outsource/grabluck/node_modules/babel/node_modules/chokidar/node_modules/fsevents
node-pre-gyp ERR! node -v v4.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.9
node-pre-gyp ERR! not ok 

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/khanguyen/.nvm/versions/node/v4.1.0/bin/node" "/Users/khanguyen/CodeProjects/Outsource/grabluck/node_modules/electron-rebuild/node_modules/npm/bin/npm-cli.js" "rebuild" "--target=0.30.7" "--arch=x64"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.5
npm ERR! code ELIFECYCLE
npm ERR! fsevents@1.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fsevents@1.0.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/khanguyen/CodeProjects/Outsource/grabluck/node_modules/npm-debug.log

Process exited with code: 1
Error: Process exited with code: 1
    at ChildProcess.<anonymous> (/Users/khanguyen/CodeProjects/Outsource/grabluck/node_modules/electron-rebuild/lib/spawn.js:55:26)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:817:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/khanguyen/.nvm/versions/node/v4.1.0/bin/node" "/Users/khanguyen/.nvm/versions/node/v4.1.0/bin/npm" "run" "rebuild"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE
npm ERR! grabluck@1.0.0 rebuild: `electron-rebuild`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the grabluck@1.0.0 rebuild script 'electron-rebuild'.
npm ERR! This is most likely a problem with the grabluck package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls grabluck
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/khanguyen/CodeProjects/Outsource/grabluck/npm-debug.log
```

**Comment by maxogden** [comment]
@nlhkh try using v0.33.1 for now, 0.30.7 isn't actually the latest, we're working on fixing that

**Comment by nlhkh** [comment]
@maxogden thanks! I just want to notify the issue :)

**Comment by mafintosh** [comment]
@nlhkh if you reinstall electron-prebuilt now you should get 0.33.1 again (which i think has the features you are looking for)

**Comment by nlhkh** [comment]
I did the reinstall. I still get the error that version `0.33.1` is not supported. Interestingly enough that when I tried version `0.33.0`, I got the same error with the corresponding version number. I wonder if there is something broken with electron-rebuild. I am using Node v4.1.0.

**Comment by mafintosh** [comment]
@nlhkh hmm weird. could you share the commands you are running?

**Comment by mafintosh** [comment]
@nlhkh OHHH i just noticed it says electron-rebuild in your gist above. Did you mean to open that issue here? This is electron-prebuilt

**Comment by nlhkh** [comment]
My apology. I realized that a few minutes ago but I thought the 2 projects were under the same umbrella at first :).

**Comment by mafintosh** [comment]
No worries. Hope you get it working.
